### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by matthieucan** [savoirfairelinux/monitoring-tools#1]
- [x] README in doc/
- [x] clean tools/
- [x] CI: integrate travis-ci
  - [x] .travis.yml and tests runner
  - [x] link to travis-ci
  - [x] fix failed tests in various plugins
    - [x] plugin-check_mem
    - [x] plugin-check_poller2livestatus (use socket instead of os.system)
    - [x] plugin-check_printer_hp_2600n (lxml is not installed, though it is in requirements)
    - [x] plugin-check_rancid (pysvn is not installed, though it is in requirements)
    - [x] plugin-check_samba
    - [x] plugin-check_spa2102 (lxml is not installed, though it is in requirements)
    - [x] plugin-check_tripplite_ups
    - [x] plugin-check_libvirt_stats (travis-ci provides Ubuntu 12.04, in which libvirt-dev is too old)
    - [x] plugin-check_linux_traffic
    - [x] travis: dont push to obs if it's a pull request (even from another branch)
  - [x] add badges
- [ ] packaging
  - [x] .deb
  - [ ] .rpm
  - [ ] tarball
- [ ] plugins library
  - [ ] write documentation for all p[lugins (hint: use --help)
  - [x] base classes
  - [ ] update plugins
  - [ ] remove jenkins .sh's
- [ ] document how-to-contribute
- [ ] static analysis
  - [ ] add lintian run in travis
- [ ] move check-foo/doc/plugin-check_foo.rst to check-foo/check_foo.rst
- [ ] travis, readthedocs and obs only changed plugins
- [x] speed-up pip install's with wheel, notably for lxml:     https://pip.pypa.io/en/latest/reference/pip_wheel.html#examples
  
  http://clarete.li/curdling/

**Comment by gst** [comment]
should clean or fill / complete the tasks list and this ticket by the way ??

**Comment by ReAzem** [comment]
Just check them.

**Comment by gst** [comment]
I've checked `speed-up pip install's with wheel, notably for lxml`

it's now correctly effective for some time :) but we could use an external "wheel location" eventually ?
